#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

/// [`GainSTM`] transmission mode.
///
/// [`GainSTM`]: crate::datagram::GainSTM
enum class GainSTMMode : uint8_t {
  /// This mode uses both phase and intensity data.
  PhaseIntensityFull = 0,
  /// This mode uses only phase data.
  PhaseFull = 1,
  /// This mode uses only half-compressed phase data.
  PhaseHalf = 2,
};

/// Silencer target.
enum class SilencerTarget : uint8_t {
  /// Apply the silencer to the intensity (before [`PulseWidthEncoder`]).
  ///
  /// [`PulseWidthEncoder`]: crate::datagram::PulseWidthEncoder
  Intensity = 0,
  /// Apply the silencer to the pulse width (after [`PulseWidthEncoder`]).
  ///
  /// [`PulseWidthEncoder`]: crate::datagram::PulseWidthEncoder
  PulseWidth = 1,
};

} // namespace autd3::native_methods
