#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>
#include "autd3/native_methods/def.hpp"

namespace autd3::native_methods {

struct LinkSimulatorBuilderPtr {
  const void *_0;
};

struct ResultLinkSimulatorBuilder {
  LinkSimulatorBuilderPtr result;
  uint32_t err_len;
  const void* err;
};

extern "C" {

[[nodiscard]] LinkSimulatorBuilderPtr AUTDLinkSimulator(uint16_t port);

[[nodiscard]]
ResultLinkSimulatorBuilder AUTDLinkSimulatorWithAddr(LinkSimulatorBuilderPtr simulator,
                                                     const char *addr);

[[nodiscard]]
LinkSimulatorBuilderPtr AUTDLinkSimulatorWithTimeout(LinkSimulatorBuilderPtr simulator,
                                                     uint64_t timeout_ns);

[[nodiscard]] LinkBuilderPtr AUTDLinkSimulatorIntoBuilder(LinkSimulatorBuilderPtr simulator);

[[nodiscard]]
FfiFutureResultI32 AUTDLinkSimulatorUpdateGeometry(LinkPtr simulator,
                                                     GeometryPtr geometry);

} // extern "C"

} // namespace autd3::native_methods
