#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

constexpr const uint32_t NUM_TRANS_IN_UNIT = 249;

constexpr const uint32_t NUM_TRANS_IN_X = 18;

constexpr const uint32_t NUM_TRANS_IN_Y = 14;

constexpr const float TRANS_SPACING_MM = 10.16;

constexpr const float DEVICE_HEIGHT_MM = 151.4;

constexpr const float DEVICE_WIDTH_MM = 192.0;

constexpr const int32_t AUTD3_ERR = -1;

constexpr const int32_t AUTD3_TRUE = 1;

constexpr const int32_t AUTD3_FALSE = 0;

enum class DebugTypeTag : uint8_t {
  None = 0,
  BaseSignal = 1,
  Thermo = 2,
  ForceFan = 3,
  Sync = 4,
  ModSegment = 5,
  ModIdx = 6,
  StmSegment = 7,
  StmIdx = 8,
  IsStmMode = 9,
  PwmOut = 10,
  Direct = 11,
};

enum class GPIOIn : uint8_t {
  I0 = 0,
  I1 = 1,
  I2 = 2,
  I3 = 3,
};

enum class GPIOOut : uint8_t {
  O0 = 0,
  O1 = 1,
  O2 = 2,
  O3 = 3,
};

enum class GainSTMMode : uint8_t {
  PhaseIntensityFull = 0,
  PhaseFull = 1,
  PhaseHalf = 2,
};

enum class SamplingConfigTag : uint8_t {
  Division = 0,
  DivisionRaw = 1,
  Freq = 2,
  FreqNearest = 3,
};

enum class Segment : uint8_t {
  S0 = 0,
  S1 = 1,
};

enum class SyncMode : uint8_t {
  FreeRun = 0,
  DC = 1,
};

enum class TransitionModeTag : uint8_t {
  SyncIdx = 0,
  SysTime = 1,
  Gpio = 2,
  Ext = 3,
  Immediate = 4,
};

struct ContextPtr {
  void* _0;
};

struct LoopBehavior {
  uint32_t rep;
};

struct TransitionModeWrap {
  TransitionModeTag tag;
  uint64_t value;
};

union SamplingConfigValue {
  uint32_t div;
  uint32_t freq;
  float freq_nearest;
};

struct SamplingConfigWrap {
  SamplingConfigTag tag;
  SamplingConfigValue value;
};

struct DevicePtr {
  void* _0;
};

struct TransducerPtr {
  void* _0;
};

struct GeometryPtr {
  void* _0;
};

struct ModulationPtr {
  void* _0;
};

struct GainPtr {
  void* _0;
};

struct LinkPtr {
  void* _0;
};

struct DatagramPtr {
  void* _0;
};

struct LinkBuilderPtr {
  void* _0;
};

struct ResultI32 {
  int32_t result;
  uint32_t err_len;
  void* err;
};

struct ResultModulation {
  ModulationPtr result;
  uint32_t err_len;
  void* err;
};

struct ResultDatagram {
  DatagramPtr result;
  uint32_t err_len;
  void* err;
};

struct Drive {
  uint8_t phase;
  uint8_t intensity;
};

struct GainSTMPtr {
  void* _0;
};

struct FociSTMPtr {
  void* _0;
};

struct ResultGainSTM {
  GainSTMPtr result;
  uint32_t err_len;
  void* err;
};

struct ResultFociSTM {
  FociSTMPtr result;
  uint32_t err_len;
  void* err;
};

struct DebugTypeWrap {
  DebugTypeTag ty;
  uint16_t value;
};

} // namespace autd3::native_methods
