#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

/// The option of [`Plane`].
struct PlaneOption {
  /// The intensity of the wave.
  Intensity intensity;
  /// The phase offset of the wave.
  Phase phase_offset;
};

/// The option of [`Focus`].
struct FocusOption {
  /// The intensity of the focus.
  Intensity intensity;
  /// The phase offset of the focus.
  Phase phase_offset;
};

/// The option of [`Bessel`].
struct BesselOption {
  /// The intensity of the beam.
  Intensity intensity;
  /// The phase offset of the beam.
  Phase phase_offset;
};

}  // namespace autd3::native_methods
