#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

extern "C" {

[[nodiscard]]
ResultModulation AUTDModulationAudioFileWav(const char *path,
                                            LoopBehavior loop_behavior);

[[nodiscard]]
ResultModulation AUTDModulationAudioFileRawPCM(const char *path,
                                               SamplingConfig config,
                                               LoopBehavior loop_behavior);

[[nodiscard]]
ResultModulation AUTDModulationAudioFileCsv(const char *path,
                                            SamplingConfig config,
                                            uint8_t deliminator,
                                            LoopBehavior loop_behavior);

} // extern "C"

} // namespace autd3::native_methods
