#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

struct ControllerPtr {
  void* _0;
};

struct FirmwareVersionListPtr {
  void* _0;
};

struct ResultFirmwareVersionList {
  FirmwareVersionListPtr result;
  uint32_t err_len;
  void* err;
};

struct ControllerBuilderPtr {
  void* _0;
};

struct ResultController {
  ControllerPtr result;
  uint32_t err_len;
  void* err;
};

struct GroupKVMapPtr {
  void* _0;
};

struct GainCalcDrivesMapPtr {
  void* _0;
};

struct ResultGainCalcDrivesMap {
  GainCalcDrivesMapPtr result;
  uint32_t err_len;
  void* err;
};

struct ContextPtr {
  void* _0;
};

struct GroupGainMapPtr {
  void* _0;
};

struct LinkAuditBuilderPtr {
  void* _0;
};

struct ModulationCalcPtr {
  void* _0;
};

struct ResultModulationCalc {
  ModulationCalcPtr result;
  uint32_t err_len;
  void* err;
};

extern "C" {

[[nodiscard]] ResultI32 AUTDControllerClose(ControllerPtr cnt);

ResultI32 AUTDControllerDelete(ControllerPtr cnt);

[[nodiscard]] ResultI32 AUTDControllerFPGAState(ControllerPtr cnt, int32_t *out);

[[nodiscard]] ResultFirmwareVersionList AUTDControllerFirmwareVersionListPointer(ControllerPtr cnt);

void AUTDControllerFirmwareVersionGet(FirmwareVersionListPtr p_info_list, uint32_t idx, char *info);

void AUTDControllerFirmwareVersionListPointerDelete(FirmwareVersionListPtr p_info_list);

void AUTDFirmwareLatest(char *latest);

[[nodiscard]]
ResultI32 AUTDControllerSend(ControllerPtr cnt,
                             DatagramPtr d1,
                             DatagramPtr d2,
                             int64_t timeout_ns);

[[nodiscard]] ControllerBuilderPtr AUTDControllerBuilder(uint32_t ultrasound_freq);

ControllerBuilderPtr AUTDControllerBuilderAddDevice(ControllerBuilderPtr builder,
                                                    double x,
                                                    double y,
                                                    double z,
                                                    double qw,
                                                    double qx,
                                                    double qy,
                                                    double qz);

[[nodiscard]]
ResultController AUTDControllerOpen(ControllerBuilderPtr builder,
                                    LinkBuilderPtr link_builder,
                                    int64_t timeout_ns);

[[nodiscard]] GroupKVMapPtr AUTDControllerGroupCreateKVMap();

void AUTDControllerGroupKVMapSet(GroupKVMapPtr map,
                                 int32_t key,
                                 DatagramPtr d1,
                                 DatagramPtr d2,
                                 int64_t timeout_ns);

[[nodiscard]]
ResultI32 AUTDControllerGroup(ControllerPtr cnt,
                              const int32_t *map,
                              GroupKVMapPtr kv_map);

[[nodiscard]] DatagramPtr AUTDDatagramClear();

[[nodiscard]] DatagramPtr AUTDDatagramDebugSettings(void* f, void* context, GeometryPtr geometry);

[[nodiscard]] DatagramPtr AUTDDatagramForceFan(void* f, void* context, GeometryPtr geometry);

[[nodiscard]]
DatagramPtr AUTDDatagramPhaseFilterAdditive(void* f,
                                            void* context,
                                            GeometryPtr geometry);

[[nodiscard]] ResultDatagram AUTDDatagramPulseWidthEncoder(const uint16_t *buf, uint32_t len);

[[nodiscard]] DatagramPtr AUTDDatagramPulseWidthEncoderDefault();

[[nodiscard]] DatagramPtr AUTDDatagramReadsFPGAState(void* f, void* context, GeometryPtr geometry);

[[nodiscard]]
ResultDatagram AUTDDatagramSilencerFixedUpdateRate(uint16_t value_intensity,
                                                   uint16_t value_phase);

[[nodiscard]]
ResultDatagram AUTDDatagramSilencerFixedCompletionSteps(uint16_t value_intensity,
                                                        uint16_t value_phase,
                                                        bool strict_mode);

[[nodiscard]] bool AUTDDatagramSilencerFixedCompletionStepsIsDefault(DatagramPtr silencer);

[[nodiscard]] FocusSTMPtr AUTDSTMFocusFromFreq(double freq);

[[nodiscard]] FocusSTMPtr AUTDSTMFocusFromFreqNearest(double freq);

[[nodiscard]] FocusSTMPtr AUTDSTMFocusFromSamplingConfig(SamplingConfigWrap config);

[[nodiscard]]
FocusSTMPtr AUTDSTMFocusAddFoci(FocusSTMPtr stm,
                                const double *points,
                                const uint8_t *intensities,
                                uint64_t size);

[[nodiscard]] FocusSTMPtr AUTDSTMFocusWithLoopBehavior(FocusSTMPtr stm, LoopBehavior loop_behavior);

[[nodiscard]] DatagramPtr AUTDSTMFocusIntoDatagramWithSegment(FocusSTMPtr stm, Segment segment);

[[nodiscard]]
DatagramPtr AUTDSTMFocusIntoDatagramWithSegmentTransition(FocusSTMPtr stm,
                                                          Segment segment,
                                                          TransitionModeWrap transition_mode);

[[nodiscard]] DatagramPtr AUTDSTMFocusIntoDatagram(FocusSTMPtr stm);

[[nodiscard]] GainSTMPtr AUTDSTMGainFromFreq(double freq);

[[nodiscard]] GainSTMPtr AUTDSTMGainFromFreqNearest(double freq);

[[nodiscard]] GainSTMPtr AUTDSTMGainFromSamplingConfig(SamplingConfigWrap config);

[[nodiscard]] GainSTMPtr AUTDSTMGainWithMode(GainSTMPtr stm, GainSTMMode mode);

[[nodiscard]] GainSTMPtr AUTDSTMGainAddGains(GainSTMPtr stm, const GainPtr *gains, uint32_t size);

[[nodiscard]] GainSTMPtr AUTDSTMGainWithLoopBehavior(GainSTMPtr stm, LoopBehavior loop_behavior);

[[nodiscard]] DatagramPtr AUTDSTMGainIntoDatagramWithSegment(GainSTMPtr stm, Segment segment);

[[nodiscard]]
DatagramPtr AUTDSTMGainIntoDatagramWithSegmentTransition(GainSTMPtr stm,
                                                         Segment segment,
                                                         TransitionModeWrap transition_mode);

[[nodiscard]] DatagramPtr AUTDSTMGainIntoDatagram(GainSTMPtr stm);

[[nodiscard]] DatagramPtr AUTDDatagramSynchronize();

[[nodiscard]]
DatagramPtr AUTDDatagramSwapSegmentModulation(Segment segment,
                                              TransitionModeWrap transition_mode);

[[nodiscard]]
DatagramPtr AUTDDatagramSwapSegmentFocusSTM(Segment segment,
                                            TransitionModeWrap transition_mode);

[[nodiscard]]
DatagramPtr AUTDDatagramSwapSegmentGainSTM(Segment segment,
                                           TransitionModeWrap transition_mode);

[[nodiscard]] DatagramPtr AUTDDatagramChangeGainSegment(Segment segment);

[[nodiscard]] uint64_t AUTDDcSysTimeNow();

[[nodiscard]] LoopBehavior AUTDLoopBehaviorInfinite();

[[nodiscard]] LoopBehavior AUTDLoopBehaviorFinite(uint32_t v);

[[nodiscard]] LoopBehavior AUTDLoopBehaviorOnce();

[[nodiscard]] uint8_t AUTDPhaseFromRad(double value);

[[nodiscard]] double AUTDPhaseToRad(uint8_t value);

[[nodiscard]] SamplingConfigWrap AUTDSamplingConfigFromDivision(uint32_t div);

[[nodiscard]] SamplingConfigWrap AUTDSamplingConfigFromDivisionRaw(uint32_t div);

[[nodiscard]] SamplingConfigWrap AUTDSamplingConfigFromFreq(uint32_t f);

[[nodiscard]] SamplingConfigWrap AUTDSamplingConfigFromFreqNearest(double f);

[[nodiscard]] DebugTypeWrap AUTDDebugTypeNone();

[[nodiscard]] DebugTypeWrap AUTDDebugTypeBaseSignal();

[[nodiscard]] DebugTypeWrap AUTDDebugTypeThermo();

[[nodiscard]] DebugTypeWrap AUTDDebugTypeForceFan();

[[nodiscard]] DebugTypeWrap AUTDDebugTypeSync();

[[nodiscard]] DebugTypeWrap AUTDDebugTypeModSegment();

[[nodiscard]] DebugTypeWrap AUTDDebugTypeModIdx(uint16_t value);

[[nodiscard]] DebugTypeWrap AUTDDebugTypeStmSegment();

[[nodiscard]] DebugTypeWrap AUTDDebugTypeStmIdx(uint16_t value);

[[nodiscard]] DebugTypeWrap AUTDDebugTypeIsStmMode();

[[nodiscard]] DebugTypeWrap AUTDDebugTypePwmOut(TransducerPtr value);

[[nodiscard]] DebugTypeWrap AUTDDebugTypeDirect(bool value);

[[nodiscard]] TransitionModeWrap AUTDTransitionModeSyncIdx();

[[nodiscard]] TransitionModeWrap AUTDTransitionModeSysTime(uint64_t sys_time);

[[nodiscard]] TransitionModeWrap AUTDTransitionModeGPIO(GPIOIn gpio);

[[nodiscard]] TransitionModeWrap AUTDTransitionModeExt();

[[nodiscard]] TransitionModeWrap AUTDTransitionModeImmediate();

[[nodiscard]]
DatagramPtr AUTDGainIntoDatagramWithSegment(GainPtr gain,
                                            Segment segment,
                                            bool update_segment);

[[nodiscard]] DatagramPtr AUTDGainIntoDatagram(GainPtr gain);

[[nodiscard]] ResultGainCalcDrivesMap AUTDGainCalc(GainPtr gain, GeometryPtr geometry);

void AUTDGainCalcGetResult(GainCalcDrivesMapPtr src, Drive *dst, uint32_t idx);

void AUTDGainCalcFreeResult(GainCalcDrivesMapPtr src);

[[nodiscard]]
GainPtr AUTDGainBessel(double x,
                       double y,
                       double z,
                       double nx,
                       double ny,
                       double nz,
                       double theta_z,
                       uint8_t intensity,
                       uint8_t phase_offset);

[[nodiscard]] bool AUTDGainBesselIsDefault(GainPtr bessel);

[[nodiscard]] GainPtr AUTDGainCustom(void* f, ContextPtr context, GeometryPtr geometry);

[[nodiscard]]
GainPtr AUTDGainFocus(double x,
                      double y,
                      double z,
                      uint8_t intensity,
                      uint8_t phase_offset);

[[nodiscard]] bool AUTDGainFocusIsDefault(GainPtr focus);

[[nodiscard]]
GroupGainMapPtr AUTDGainGroupCreateMap(const uint32_t *device_indices_ptr,
                                       uint32_t num_devices);

[[nodiscard]]
GroupGainMapPtr AUTDGainGroupMapSet(GroupGainMapPtr map,
                                    uint32_t dev_idx,
                                    const int32_t *map_data);

[[nodiscard]]
GainPtr AUTDGainGroup(GroupGainMapPtr map,
                      const int32_t *keys_ptr,
                      const GainPtr *values_ptr,
                      uint32_t kv_len);

[[nodiscard]] GainPtr AUTDGainNull();

[[nodiscard]]
GainPtr AUTDGainPlane(double nx,
                      double ny,
                      double nz,
                      uint8_t intensity,
                      uint8_t phase_offset);

[[nodiscard]] bool AUTDGainPlanelIsDefault(GainPtr plane);

[[nodiscard]] GainPtr AUTDGainRaw();

[[nodiscard]]
GainPtr AUTDGainRawSet(GainPtr custom,
                       uint32_t dev_idx,
                       const Drive *ptr,
                       uint32_t len);

[[nodiscard]] GainPtr AUTDGainUniform(uint8_t intensity, uint8_t phase);

[[nodiscard]] bool AUTDGainUniformIsDefault(GainPtr uniform);

[[nodiscard]] GeometryPtr AUTDGeometry(ControllerPtr cnt);

[[nodiscard]] uint32_t AUTDGeometryNumDevices(GeometryPtr geo);

[[nodiscard]] DevicePtr AUTDDevice(GeometryPtr geo, uint32_t dev_idx);

[[nodiscard]] uint32_t AUTDDeviceNumTransducers(DevicePtr dev);

[[nodiscard]] double AUTDDeviceGetSoundSpeed(DevicePtr dev);

void AUTDDeviceSetSoundSpeed(DevicePtr dev, double value);

void AUTDDeviceSetSoundSpeedFromTemp(DevicePtr dev, double temp, double k, double r, double m);

[[nodiscard]] double AUTDDeviceGetAttenuation(DevicePtr dev);

void AUTDDeviceSetAttenuation(DevicePtr dev, double value);

void AUTDDeviceCenter(DevicePtr dev, double *center);

void AUTDDeviceTranslate(DevicePtr dev, double x, double y, double z);

void AUTDDeviceRotate(DevicePtr dev, double w, double i, double j, double k);

void AUTDDeviceAffine(DevicePtr dev,
                      double x,
                      double y,
                      double z,
                      double w,
                      double i,
                      double j,
                      double k);

void AUTDDeviceEnableSet(DevicePtr dev, bool value);

[[nodiscard]] bool AUTDDeviceEnableGet(DevicePtr dev);

[[nodiscard]] double AUTDDeviceWavelength(DevicePtr dev);

[[nodiscard]] double AUTDDeviceWavenumber(DevicePtr dev);

void AUTDRotationFromEulerZYZ(double x, double y, double z, double *rot);

[[nodiscard]] TransducerPtr AUTDTransducer(DevicePtr dev, uint32_t idx);

void AUTDTransducerPosition(TransducerPtr tr, double *pos);

void AUTDTransducerRotation(TransducerPtr tr, double *rot);

void AUTDTransducerDirectionX(TransducerPtr tr, double *dir);

void AUTDTransducerDirectionY(TransducerPtr tr, double *dir);

void AUTDTransducerDirectionZ(TransducerPtr tr, double *dir);

[[nodiscard]] LinkPtr AUTDLinkGet(ControllerPtr cnt);

[[nodiscard]] LinkAuditBuilderPtr AUTDLinkAudit();

[[nodiscard]]
LinkAuditBuilderPtr AUTDLinkAuditWithTimeout(LinkAuditBuilderPtr audit,
                                             uint64_t timeout_ns);

[[nodiscard]] LinkBuilderPtr AUTDLinkAuditIntoBuilder(LinkAuditBuilderPtr audit);

[[nodiscard]] bool AUTDLinkAuditIsOpen(LinkPtr audit);

[[nodiscard]] uint64_t AUTDLinkAuditTimeoutNs(LinkPtr audit);

[[nodiscard]] int64_t AUTDLinkAuditLastTimeoutNs(LinkPtr audit);

void AUTDLinkAuditDown(LinkPtr audit);

void AUTDLinkAuditBreakDown(LinkPtr audit);

[[nodiscard]] uint32_t AUTDLinkAuditCpuNumTransducers(LinkPtr audit, uint32_t idx);

void AUTDLinkAuditFpgaAssertThermalSensor(LinkPtr audit, uint32_t idx);

void AUTDLinkAuditFpgaDeassertThermalSensor(LinkPtr audit, uint32_t idx);

[[nodiscard]] bool AUTDLinkAuditFpgaIsForceFan(LinkPtr audit, uint32_t idx);

[[nodiscard]] Segment AUTDLinkAuditFpgaCurrentStmSegment(LinkPtr audit, uint32_t idx);

[[nodiscard]] Segment AUTDLinkAuditFpgaCurrentModSegment(LinkPtr audit, uint32_t idx);

[[nodiscard]] bool AUTDLinkAuditFpgaIsStmGainMode(LinkPtr audit, Segment segment, uint32_t idx);

[[nodiscard]] uint16_t AUTDLinkAuditFpgaSilencerUpdateRateIntensity(LinkPtr audit, uint32_t idx);

[[nodiscard]] uint16_t AUTDLinkAuditFpgaSilencerUpdateRatePhase(LinkPtr audit, uint32_t idx);

[[nodiscard]]
uint16_t AUTDLinkAuditFpgaSilencerCompletionStepsIntensity(LinkPtr audit,
                                                           uint32_t idx);

[[nodiscard]] uint16_t AUTDLinkAuditFpgaSilencerCompletionStepsPhase(LinkPtr audit, uint32_t idx);

[[nodiscard]] bool AUTDLinkAuditFpgaSilencerFixedCompletionStepsMode(LinkPtr audit, uint32_t idx);

void AUTDLinkAuditFpgaDebugTypes(LinkPtr audit, uint32_t idx, uint8_t *ty);

void AUTDLinkAuditFpgaDebugValues(LinkPtr audit, uint32_t idx, uint16_t *value);

[[nodiscard]]
uint32_t AUTDLinkAuditFpgaStmFreqDivision(LinkPtr audit,
                                          Segment segment,
                                          uint32_t idx);

[[nodiscard]] uint32_t AUTDLinkAuditFpgaStmCycle(LinkPtr audit, Segment segment, uint32_t idx);

[[nodiscard]] uint32_t AUTDLinkAuditFpgaSoundSpeed(LinkPtr audit, Segment segment, uint32_t idx);

[[nodiscard]]
LoopBehavior AUTDLinkAuditFpgaStmLoopBehavior(LinkPtr audit,
                                              Segment segment,
                                              uint32_t idx);

[[nodiscard]]
uint32_t AUTDLinkAuditFpgaModulationFreqDivision(LinkPtr audit,
                                                 Segment segment,
                                                 uint32_t idx);

[[nodiscard]]
uint32_t AUTDLinkAuditFpgaModulationCycle(LinkPtr audit,
                                          Segment segment,
                                          uint32_t idx);

void AUTDLinkAuditFpgaModulation(LinkPtr audit, Segment segment, uint32_t idx, uint8_t *data);

[[nodiscard]]
LoopBehavior AUTDLinkAuditFpgaModulationLoopBehavior(LinkPtr audit,
                                                     Segment segment,
                                                     uint32_t idx);

void AUTDLinkAuditFpgaDrives(LinkPtr audit,
                             Segment segment,
                             uint32_t idx,
                             uint32_t stm_idx,
                             uint8_t *intensities,
                             uint8_t *phases);

void AUTDLinkAuditFpgaPhaseFilter(LinkPtr audit, uint32_t idx, uint8_t *phase_filter);

[[nodiscard]] LinkBuilderPtr AUTDLinkNop();

[[nodiscard]] DatagramPtr AUTDModulationIntoDatagramWithSegment(ModulationPtr m, Segment segment);

[[nodiscard]]
DatagramPtr AUTDModulationIntoDatagramWithSegmentTransition(ModulationPtr m,
                                                            Segment segment,
                                                            TransitionModeWrap transition_mode);

[[nodiscard]] DatagramPtr AUTDModulationIntoDatagram(ModulationPtr m);

[[nodiscard]] ResultModulationCalc AUTDModulationCalc(ModulationPtr m, GeometryPtr geometry);

void AUTDModulationCalcGetResult(ModulationCalcPtr src, uint8_t *dst);

uint32_t AUTDModulationCalcGetSize(ModulationCalcPtr src);

void AUTDModulationCalcFreeResult(ModulationCalcPtr src);

[[nodiscard]]
ModulationPtr AUTDModulationFourierExact(const ModulationPtr *components,
                                         uint32_t size,
                                         LoopBehavior loop_behavior);

[[nodiscard]]
ModulationPtr AUTDModulationFourierExactFloat(const ModulationPtr *components,
                                              uint32_t size,
                                              LoopBehavior loop_behavior);

[[nodiscard]]
ModulationPtr AUTDModulationFourierNearest(const ModulationPtr *components,
                                           uint32_t size,
                                           LoopBehavior loop_behavior);

[[nodiscard]]
ModulationPtr AUTDModulationWithRadiationPressure(ModulationPtr m,
                                                  LoopBehavior loop_behavior);

[[nodiscard]]
ModulationPtr AUTDModulationRaw(SamplingConfigWrap config,
                                LoopBehavior loop_behavior,
                                const uint8_t *ptr,
                                uint32_t len);

[[nodiscard]]
ModulationPtr AUTDModulationSineExact(uint32_t freq,
                                      SamplingConfigWrap config,
                                      uint8_t intensity,
                                      uint8_t offset,
                                      double phase,
                                      LoopBehavior loop_behavior);

[[nodiscard]]
ModulationPtr AUTDModulationSineExactFloat(double freq,
                                           SamplingConfigWrap config,
                                           uint8_t intensity,
                                           uint8_t offset,
                                           double phase,
                                           LoopBehavior loop_behavior);

[[nodiscard]]
ModulationPtr AUTDModulationSineNearest(double freq,
                                        SamplingConfigWrap config,
                                        uint8_t intensity,
                                        uint8_t offset,
                                        double phase,
                                        LoopBehavior loop_behavior);

[[nodiscard]] bool AUTDModulationSineIsDefault(ModulationPtr sine);

[[nodiscard]]
ModulationPtr AUTDModulationSquareExact(uint32_t freq,
                                        SamplingConfigWrap config,
                                        uint8_t low,
                                        uint8_t high,
                                        double duty,
                                        LoopBehavior loop_behavior);

[[nodiscard]]
ModulationPtr AUTDModulationSquareExactFloat(double freq,
                                             SamplingConfigWrap config,
                                             uint8_t low,
                                             uint8_t high,
                                             double duty,
                                             LoopBehavior loop_behavior);

[[nodiscard]]
ModulationPtr AUTDModulationSquareNearest(double freq,
                                          SamplingConfigWrap config,
                                          uint8_t low,
                                          uint8_t high,
                                          double duty,
                                          LoopBehavior loop_behavior);

[[nodiscard]] bool AUTDModulationSquareIsDefault(ModulationPtr square);

[[nodiscard]] ModulationPtr AUTDModulationStatic(uint8_t intensity, LoopBehavior loop_behavior);

[[nodiscard]] bool AUTDModulationStaticIsDefault(ModulationPtr s);

[[nodiscard]]
ModulationPtr AUTDModulationWithTransform(ModulationPtr m,
                                          void* f,
                                          void* context,
                                          LoopBehavior loop_behavior);

void AUTDGetErr(void* src, char *dst);

} // extern "C"

} // namespace autd3::native_methods
