#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

extern "C" {

[[nodiscard]] ResultLink AUTDLinkRemote(const char *addr);

}  // extern "C"

}  // namespace autd3::native_methods
