#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

struct LinkSimulatorBuilderPtr {
  const void *_0;
};

struct ResultLinkSimulatorBuilder {
  LinkSimulatorBuilderPtr result;
  uint32_t err_len;
  const void* err;
};

extern "C" {

void AUTDLinkSimulatorTracingInit();

[[nodiscard]] ResultLinkSimulatorBuilder AUTDLinkSimulator(const char *addr);

[[nodiscard]]
LinkSimulatorBuilderPtr AUTDLinkSimulatorWithTimeout(LinkSimulatorBuilderPtr simulator,
                                                     uint64_t timeout_ns);

[[nodiscard]] LinkBuilderPtr AUTDLinkSimulatorIntoBuilder(LinkSimulatorBuilderPtr simulator);

} // extern "C"

} // namespace autd3::native_methods
