#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

extern "C" {

void AUTDLinkTwinCATTracingInit();

ResultStatus AUTDLinkTwinCATTracingInitWithFile(const char *path);

[[nodiscard]] ResultLink AUTDLinkTwinCAT();

[[nodiscard]]
ResultLink AUTDLinkRemoteTwinCAT(const char *server_ams_net_id,
                                 const char *server_ip,
                                 const char *client_ams_net_id);

}  // extern "C"

}  // namespace autd3::native_methods
