name: build

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test-on-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build
      - run: cargo make build
      - run: cargo make test
        if: ${{ matrix.os != 'windows-latest' }}
      - run: cargo make test -DBUILD_LINK_ETHERCRAB_TEST=OFF
        if: ${{ matrix.os == 'windows-latest' }}
